### ISSUE TITLE
Personal record field: reps

### ISSUE THREAD

**Issue by cfilipov** [cfilipov/MuscleBook#22]
Right now there are several personal records that are displayed on the data entry screen. They are all focused in some way on _weight_. Even the xRM, shows the max weight for X reps of that exercise.

It would be useful to also have "max reps" field (for bodyweight exercises especially, but not exclusively). This would tell you how many reps max you have performed for a given weight. Basically the inverse of xRM. 

Question, whats a good name for this?

**Comment by JonathanGuberman** [comment]
Why not just "max reps"?

**Comment by cfilipov** [comment]
Yeah, seems obvious. I honestly don't remember why I was confused on the naming.

**Comment by cfilipov** [comment]
Now I remember. I had issue #23 in mind when I was writing that comment. I don't know what to call the inverse of the e1rm.

**Comment by cfilipov** [comment]
Done in [v0.1.0](https://github.com/cfilipov/MuscleBook/releases/tag/v0.1.0)
