### ISSUE TITLE
[Enhancement] Only show exercises that have been performed at least once in the frequency view

### ISSUE THREAD

**Issue by JonathanGuberman** [cfilipov/MuscleBook#37]
I'm not sure what to call it other than the "frequency" list of exercises (the one with the 123 icon rather than the ABC), but I think it should only display exercises that you've actually performed. Exercises that haven't been performed at all are displayed in an apparently arbitrary order that is not at all useful; if you're searching for an exercise that you've never done the alphabetical view (and search) are the way to do it.

**Comment by cfilipov** [comment]
Good idea. Will do.

**Comment by cfilipov** [comment]
Done in [v0.1.0](https://github.com/cfilipov/MuscleBook/releases/tag/v0.1.0)
