### ISSUE TITLE
[Enhancement] Make "by frequency" exercise list the default (once it's populated)

### ISSUE THREAD

**Issue by JonathanGuberman** [cfilipov/MuscleBook#38]
After doing a few workouts, I only use the frequency view to select exercises. It's annoying to have to click past the alphabetical view every time I change exercises, and I think the most common use-case will be to stick with one's most frequent exercises rather than try new ones all the time, anyways.

**Comment by cfilipov** [comment]
Done in [v0.1.0](https://github.com/cfilipov/MuscleBook/releases/tag/v0.1.0)
