### ISSUE TITLE
[Bug] When editing a data point, the weight in the the workout summary doesn't update until refreshed

### ISSUE THREAD

**Issue by JonathanGuberman** [cfilipov/MuscleBook#40]
I think the title says it all, but just in case:
1. Enter "Workout Summary" view and select a data point.
2. Choose "Edit" and update the "weight" field.
3. Return to "Workout Summary," and the old weight is displayed.
4. Exit "Workout Summary" and then re-open it, and the updated weight is now displayed.

**Comment by cfilipov** [comment]
Fixed in v0.1.1
